version: '3'
services:
  nextjs-accelerator-container:
    container_name: nextjs-accelerator
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/nextjs-accelerator-workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  nextjs-accelerator-workspace:
    name: nextjs-accelerator-workspace
